# This file contains values from Cookiecutter

default_context:
  project_name: "amazon-ynab"
  project_description:
    "Amazon YNAB is a reconciler that scrapes Amazon orders and adds memo info on each
    corresponding YNAB transaction"
  organization: "self"
  license: "MIT"
  minimal_python_version: "3.10"
  github_name: "sbarrios93"
  email: "sbarrios93@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
