name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Install Rye
        uses: sbarrios93/rye-rust-action@v0.1.0

      - name: Set up Python ${{ matrix.python-version }}
        run: rye pin ${{ matrix.python-version }}

      - name: Set up cache
        uses: actions/cache@v3.3.1
        id: venv-cache
        with:
          path: .venv
          key:
            venv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}-${{
            hashFiles('requirements.lock') }}-${{ hashFiles('requirements-dev.lock') }}-

      - name: Install dependencies
        run: |
          rye sync

      - name: pre-commit
        run: |
          rye run pre-commit run --all-files --show-diff-on-failure --color always

      - name: Run tests
        run: |
          make test

      - name: Run safety checks
        run: |
          make check-safety
