name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Update local toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version

      - name: Get Rye commit hash
        id: rye-commit-hash
        run: |
          echo "::set-output name=hash::$(git ls-remote https://github.com/mitsuhiko/rye.git HEAD | cut -f 1)"

      - name: Set up Rye cache
        uses: actions/cache@v3.3.1
        with:
          path: ~/.cargo/bin/rye
          key:
            rye-cargo-${{ runner.os }}-stable-${{ steps.rye-commit-hash.outputs.hash }}

      - name: Install Rye
        run: cargo install --git https://github.com/mitsuhiko/rye rye

      - name: Set up Python ${{ matrix.python-version }}
        run: rye pin ${{ matrix.python-version }}

      - name: Set up cache
        uses: actions/cache@v3.3.1
        with:
          path: .venv
          key:
            venv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}-${{
            hashFiles('requirements.lock') }}-${{ hashFiles('requirements-dev.lock') }}-

      - name: Install dependencies
        run: |
          rye sync

      - name: pre-commit
        run: |
          rye install pre-commit
          pre-commit run --all-files --show-diff-on-failure --color always

      - name: Run tests
        run: |
          make test

      - name: Run safety checks
        run: |
          make check-safety
